[package]
name = "evm_rpc"
version = "0.1.0"
description = "Interact with EVM blockchains from the Internet Computer."
authors = ["DFINITY Foundation"]
readme = "README.md"
edition = "2021"

[profile.release]
debug = false
lto = true
strip = true
opt-level = 's'

# Required by `ic-test-utilities-load-wasm`
[profile.canister-release]
inherits = "release"

[dependencies]
async-trait = "0.1"
candid = { workspace = true }
dfn_core = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
getrandom = { workspace = true }
hex = "0.4"
ic-canister-log = { git = "https://github.com/dfinity/ic", rev = "2e79e7af9a6fa15633d73af69fb021a0ae74df6c" }
ic-canisters-http-types = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-macros = { workspace = true }
ic-certified-map = { workspace = true }
ic-cketh-minter = { git = "https://github.com/dfinity/ic", rev = "2e79e7af9a6fa15633d73af69fb021a0ae74df6c" }
ic-crypto-sha3 = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
ic-metrics-encoder = { workspace = true }
ic-stable-structures = { workspace = true }
maplit = "1.0"
num = "0.4"
num-traits = "0.2"
num-derive = "0.4"
serde = "1.0"
serde_json = "1.0"
url = "2.4"

[dev-dependencies]
assert_matches = "1.5"
ic-base-types = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
ic-config = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
ic-ic00-types = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
ic-state-machine-tests = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
ic-test-utilities-load-wasm = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }

[workspace.dependencies]
candid = { version = "0.9" }
getrandom = { version = "0.2", features = ["custom"] }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", rev = "ca5e5052886de781021506814d2c6502e375da48" }
ic-certified-map = "0.4"
ic-cdk = "0.10"
ic-cdk-bindgen = "0.1"
ic-cdk-macros = "0.7"
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5"

[workspace]
members = ["e2e/rust"]
