name: Bazel

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "README.md"
jobs:
  pin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: Swatinem/rust-cache@v2

      - name: Bazel pin
        run: scripts/bazel-pin

      - name: Check unchanged
        run: git diff -q

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: Swatinem/rust-cache@v2

      #   - name: Install dfx
      #     uses: dfinity/setup-dfx@main

      #   - name: Start dfx
      #     run: dfx start --background

      - name: Bazel build
        run: bazel build evm_rpc
